### ISSUE TITLE
Feed breaks if there are more posts than the pagination size

### ISSUE THREAD

**Issue by frankieroberto** [x-govuk/govuk-eleventy-plugin#330]
If you follow [the instructions for feeds](https://x-govuk.github.io/govuk-eleventy-plugin/feed/) but have more posts in the feed than specified in the pagination size, it breaks with the error message:

```
Output conflict: multiple input files are writing to `_site/posts/feed.xml`. Use distinct `permalink` values to resolve this conflict.
[11ty]   1. ./app/feed.njk
[11ty]   2. ./app/feed.njk (via DuplicatePermalinkOutputError)
```

Need to find a way to only include the most recent x items in the feed rather than one file per page.

**Comment by paulrobertlloyd** [comment]
Ah, this is probably why we didn’t use pagination in the first place; it’s going to try and create a second file, also called feed.xml.

Why did we move to using `pagination` again? Anyway, I think the `feed.njk` layout will need to be reverted, to something more along the lines of

```diff
- {%- for item in pagination.items %}
+ {%- for item in collections.post | limit: size | reverse %}
```

And the documentation updated to use the following front matter:

```yaml
---
eleventyExcludeFromCollections: true
layout: feed
permalink: /feed.xml
size: 20
---
```

---

I note that we’re using `collections.post` in that template anyway, so the collection to pull items from was never truly configurable. We can keep it so that you can use a different collection, with something like this:

```diff
-   <updated>{{ collections.post | getNewestCollectionItemDate | dateToRfc3339 }}</updated>
+   <updated>{{ collections[collection] | getNewestCollectionItemDate | dateToRfc3339 }}</updated>

- {%- for item in pagination.items %}
+ {%- for item in collections[collection] | limit: size | reverse %}
```

And use the following front matter:

```yaml
---
eleventyExcludeFromCollections: true
layout: feed
permalink: /feed.xml
collection: posts
size: 20
---
```

Want to try that?
